### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by ghost** [Mobilization/2017.mobilization.pl#4]
Hi,

during checking the conference site, I've found some typos:

1. `Łódźarea`
2. 'specialised' - there is verb`specialise`, but I'm pretty sure the adjective is `specialized`
3. `fast paced` - shouldn't be `fast-paced`?
4. `I my talk, Ill introduce you`, there should be `I'll`
5. ` I am the developper and maintainer` - you know where ;-)

Tell me what you think of it.

If you mind, I can create MR with fixed code. Just let me know.

Cheers!

**Comment by marekdef** [comment]
Some of those come from the c4p for so the speaker sent us this. 
Ofc we should review but the time is against us

If you be so nice please create PR with fixes

**Comment by marciniwanicki** [comment]
👍 PR would be great! Many thanks @piotrek1543!
