### ISSUE TITLE
[Mobile] Click on speaker photo automatically open link

### ISSUE THREAD

**Issue by ghost** [Mobilization/2017.mobilization.pl#6]
Hi,

already tested on Huawei P8 Lite. Choosing any of speakers open one of additional profile links instead of modal with description and links in footer.

Cheers!

**Comment by marciniwanicki** [comment]
Hi @piotrek1543,

I will try to fix it today, hopefully I will be able to reproduce it on my mobile devices. 

Thanks for your support!
